name: pypi-release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install poetry
        run: |
          python -m pip install poetry

      - name: Install Dynamic Versioning Plugin
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"

      - name: Build and publish
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry build
          poetry config pypi-token.pypi $PYPI_API_TOKEN
          poetry publish
