name: release new version of pypi package  

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install poetry
        run: |
          python -m pip install poetry
          
      - name: poetry build
        run: |
          poetry build    
          
      - name: poetry config pypi token
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry config pypi-token.pypi "$PYPI_API_TOKEN"
          
      - name: poetry publish
        run: |
          poetry publish
